# Generated by Django 5.0.2 on 2026-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0003_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('materia', models.CharField(max_length=150)),
                ('docente', models.CharField(blank=True, max_length=150)),
                ('semestre', models.CharField(max_length=50)),
                ('cupo_max', models.PositiveIntegerField()),
                ('inscritos', models.PositiveIntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo', 'id'],
            },
        ),
    ]
