# Generated by Django 5.0.2 on 2026-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0004_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('recursos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso')], default='Disponible', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['edificio', 'numero', 'id'],
                'unique_together': {('edificio', 'numero')},
            },
        ),
    ]
