# Generated by Django 5.0.2 on 2026-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0005_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='semestre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
