# Generated by Django 5.0.2 on 2026-04-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0007_update_aula_estado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('Cambio de Aula', 'Cambio de Aula'), ('Reporte de Falla Tecnica', 'Reporte de Falla Tecnica'), ('Solicitud de Material', 'Solicitud de Material'), ('Ajuste de Horario', 'Ajuste de Horario')], max_length=60)),
                ('aula', models.CharField(max_length=120)),
                ('motivo', models.CharField(max_length=200)),
                ('informacion_adicional', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('admin_resuelve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to='EduPlan_API.administrador')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='EduPlan_API.docente')),
            ],
            options={
                'ordering': ['-fecha_solicitud', '-id'],
            },
        ),
    ]
