# Generated by Django 5.0.2 on 2026-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0008_solicituddocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='dia_semana',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
