# Generated by Django 5.0.2 on 2026-04-21 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0010_grupo_dias_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='EduPlan_API.grupo')),
            ],
            options={
                'ordering': ['fecha_entrega', 'id'],
            },
        ),
    ]
