# Generated by Django 5.0.2 on 2026-04-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0011_tareacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cubiculo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='docente',
            name='departamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='docente',
            name='especializacion',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
