# Generated by Django 5.0.2 on 2026-04-21 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduPlan_API', '0012_docente_cubiculo_docente_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='EduPlan_API.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='EduPlan_API.grupo')),
            ],
            options={
                'ordering': ['-fecha_inscripcion', '-id'],
                'unique_together': {('estudiante', 'grupo')},
            },
        ),
    ]
